# -*- coding: utf-8 -*-
"""01_인구소멸위기지역_전처리.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nBJG4USYbVfAAokgkxbo5CahzZpzqNmO

# 인구소멸 위기지역 - 전처리 (Part 1)
"""

import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

from google.colab import drive
drive.mount('/content/mnt')

data_folder = '/content/mnt/MyDrive/데이터/인구소멸위기지역'

!ls -l $data_folder

df = pd.read_csv(f'{data_folder}/시군구_성_연령_5세_별_인구2_2020.csv', encoding='euc-kr')
print(df.shape)
df.head(260).tail(5)

df['시군구'][df.행정구.notnull()] = df.행정구[df.행정구.notnull()]
df.head(260).tail()

# 소계 데이터 제외
df = df[df.시군구 != '소계']
print(df.shape)
df.head()

df['20~39세'] = df['20 - 24세'] + df['25 - 29세'] + df['30 - 34세'] + df['35 - 39세']
df['65세이상'] = df['65 - 69세'] + df['70 - 74세'] + df['75 - 79세'] + df['80세 이상']
df = df[['광역시도','시군구','구분','인구수','20~39세','65세이상']]
df.head()

# pivot_table을 만들어서 시군구 단위로 grouping
pop = pd.pivot_table(df,
                     index=['광역시도','시군구'], columns=['구분'],
                     values=['인구수','20~39세','65세이상'])
print(pop.shape)
pop.head()

# 인구 소멸비율 계산
pop['소멸비율'] = pop['20~39세','여자'] / pop['65세이상','계']
pop.head()

pop['소멸위기지역'] = pop.소멸비율 < 0.5
pop['소멸위기고위험지역'] = pop.소멸비율 < 0.2
pop.head()

